config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :questions do
    resources :answers
  end

  root to: 'questions#index'
end

app/models/answer.rb
class Answer < ActiveRecord::Base
  belongs_to :question
  validates :body, presence: true

  scope :existing, -> { where.not(id: nil) }
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/question.rb
class Question < ApplicationRecord
  has_many :answers, dependent: :delete_all

  validates :title, :body, presence: true

  def saved_answers
    answers.existing
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/answers_controller.rb
class AnswersController < ApplicationController
  before_action :authenticate_user!

  def create
    @question = Question.find(params[:question_id])
    @answer = @question.answers.create(answer_params)

      if @answer.errors.present?
        flash[:danger] = @answer.errors.full_messages.last
      else
        flash[:success] = "Answer successfully placed"
      end

    respond_to do |format|
      format.js
    end
  end

  def update
    @answer = Answer.find(params[:id])
    @answer.update(answer_params)
    @question = @answer.question

    if @answer.errors.present?
      flash[:danger] = @answer.errors.full_messages.last
    else
      flash[:success] = "Answer successfully placed"
    end
  end

  def destroy
    @answer = Answer.find(params[:id])
    @answer.destroy

    if @answer.errors.present?
      flash[:danger] = @answer.errors.full_messages.last
    else
      flash[:success] = "Answer successfully deleted"
    end

    respond_to do |format|
      format.js
    end
  end

  private

  def answer_params
    params.require(:answer).permit(:body)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  add_flash_types :danger, :info, :warning, :success
  before_action :authenticate_user!
end

app/controllers/questions_controller.rb
class QuestionsController < ApplicationController
  before_action :load_question, only: %i[show edit update destroy]
  before_action :authenticate_user!, except: %i[index show]
  def index
    @questions = Question.all
  end

  def show
    @answer = @question.answers.build
  end

  def new
    @question = Question.new
  end

  def edit; end

  def create
    @question = Question.new(question_params)
    if @question.save
      redirect_to @question
    else
      render :new
    end
  end

  def update
    if @question.update(question_params)
      redirect_to @question
    else
      render :edit
    end
  end

  def destroy
    @question.destroy
    redirect_to questions_path
  end

  private

  def load_question
    @question = Question.find(params[:id])
  end

  def question_params
    params.require(:question).permit(:title, :body)
  end
end

app/controllers/static_controller.rb
class StaticController < ApplicationController
    def index
    end
end

app/controllers/v1/questions_controller.rb
class V1::QuestionsController < ApplicationController
  before_action :load_question, only: %i[show edit update destroy]
  before_action :authenticate_user!, except: %i[index show]
  def index
    
    @questions = Question.all
      
    render json: { :questions => [
      {
        :name => 'thiname',
        :guid => 'gamnasd'
      }
     ] }.to_json
  end

  def show; end

  def new
    @question = Question.new
  end

  def edit; end

  def create
    @question = Question.new(question_params)

    if @question.save
      flash[:notice] = 'Your question successfully created!'
      redirect_to @question
    else
      render :new
    end
  end

  def update
    if @question.update(question_params)
      redirect_to @question
    else
      render :edit
    end
  end

  def destroy
    @question.destroy
    redirect_to questions_path
  end

  private

  def load_question
    @question = Question.find(params[:id])
  end

  def question_params
    params.require(:question).permit(:title, :body)
  end
end

app/helpers/answers_helper.rb
module AnswersHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/answers/create.js.erb
$('.answers').html("<%= j render './questions/answers' %>");
$("#flash").html('<%= j render partial: "shared/notice_banner" %>');

app/views/answers/destroy.js.erb
<% unless @answer.errors.present? %>
$('.answers').html("<%= j render './questions/answers' %>");
$('#answer_body').val(' ')
<% end %>

$("#flash").html('<%= j render partial: "shared/notice_banner" %>');

app/views/answers/update.js.erb
<% unless @answer.errors.present? %>
  $('.answers').html("<%= j render './questions/answers' %>");
  $('#answer_body').val(' ')
<% end %>

$("#flash").html('<%= j render partial: "shared/notice_banner" %>');

app/views/layouts/_flash.html.erb
<div id="flash">
  <% if notice.present? %>
    <%= render partial: "shared/notice_banner" %>
  <% end %>
</div>

app/views/layouts/_navbar.html.erb
<nav class="navbar navbar-expand-lg navbar-dark bg-dark static-top">
  <div class="container">
    <%= link_to "QA", root_url, class: "navbar-brand" %>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarResponsive">
      <ul class="navbar-nav ml-auto">
        <li>
          <%= link_to "New question", new_question_path, class: "nav-link" %>
        </li>
        <%- if current_user %>
          <li>
            <%= link_to "Hello, #{current_user.email}!",  new_question_path, class:"nav-link" %>
          </li>
          <li>
            <%= link_to "Logout", destroy_user_session_path, method: :delete, class:"nav-link" %>
          </li>
        <% else %>
          <li>
            <%= link_to "Login", new_user_session_path, class: "nav-link" %>
          </li>
          <li>
            <%= link_to "Sign up", new_user_registration_path, class: "nav-link" %>
          </li>
        <% end %>
      </ul>
    </div>
  </div>
</nav> 

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Qna</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>

    <%= render 'layouts/navbar' %>
    <%= render 'layouts/flash' %>

    <%= yield %>
  </body>
</html>

app/views/questions/_answer_form.html.erb
<%= form_for [@question, @answer], remote: true  do |f| %>
  <form>
    <div class="form-group">
      <%= f.label :body, "Your answer" %>
      <%= f.text_area :body, id: "answer_body", class: "form-control" %>
    </div>
  <%= f.submit 'Create', class: "btn btn-primary" %>
  </form>
<% end %>

app/views/questions/_answers.html.erb
<% @question.saved_answers.each do |answer| %>
  <p><%= answer.body %></p>
  <% if user_signed_in? %>
    <p><%= button_tag "Edit", onclick: "document.getElementById(`edit_answer_#{answer.id}`).style.display = 'block';" %></p>
      <%= form_for [@question, answer], remote: true  do |f| %>
      <form>
        <div class="form-group">
          <%= f.label :body, "Your answer" %>
          <%= f.text_area :body, id: "answer_body", class: "form-control" %>
        </div>
        <%= f.submit 'Update answer', class: "btn btn-primary" %>
      </form>
    <% end %>
  <% end %>
<% end %>

app/views/questions/_question_form.html.erb
<%= form_for @question do |f| %>
<form>
  <div class="form-group">
    <%= f.label :title, "Title" %>
    <%= f.text_field :title, id: "question_title", class: "form-control" %>
    <%= f.label :body, "Body" %>
    <%= f.text_area :body, id: "question_body", class: "form-control" %>
  </div>
  <%= f.submit 'Create', class: "btn btn-primary" %>
</form>
<% end %>

app/views/questions/index.html.erb
<p> <%= link_to 'Ask question', new_question_path %> </p>
<% @questions.each do | question | %>
<div class="card text-center">
  <div class="card-body">
    <h4 class="card-title">
      <%= link_to question.title, question_path(question) %>
    </h4>
<!--    <h6 class="card-subtitle mb-2 text-muted">Card subtitle</h6>-->
    <p class="card-text">
      Some quick example text to build on the card title
      and make up the bulk of the card's content.
    </p>
    <a class="card-link">Answers: <%= question.answers.count %></a>
    <a class="card-link">Topic starter: nil</a>
  </div>
</div>
<% end %>

app/views/questions/new.html.erb
<%= render 'questions/question_form' %>

app/views/questions/show.html.erb
<h1> <%= @question.title %> </h1>
<p> <%= @question.body %> </p>
<p> <%= link_to "Delete question", question_path(@question), method: :delete %></p>
<hr>

<div class = "answers">
  <%= render "answers" %>
</div>
<hr>

<%= render "questions/answer_form" %>

app/views/shared/_notice_banner.html.erb
<% flash.each do |name, msg| %>
  <div class = "alert alert-<%= name %>">
    <%= msg %>
  </div>
<% end %>